class FAILED_TESTS_MCDC_R0

inherit
	EQA_TEST_SET

feature -- Tests from failed proofs 

	test_QS_QUEUE
		do
				test_QS_QUEUE_make_1
				test_QS_QUEUE_enter_1
				test_QS_QUEUE_enter_2
				test_QS_QUEUE_delete_1
				test_QS_QUEUE_delete_2
				test_QS_QUEUE_delete_3
				test_QS_QUEUE_peek_1
				test_QS_QUEUE_peek_2
				test_QS_QUEUE_is_contain_1
				test_QS_QUEUE_is_contain_2
				test_QS_QUEUE_search_1
				test_QS_QUEUE_search_2
				test_QS_QUEUE_is_empty_1
				test_QS_QUEUE_is_full_1
				test_QS_QUEUE_is_full_2
				test_QS_QUEUE_size_1
				test_QS_QUEUE_get_front_1
				test_QS_QUEUE_get_rear_1
				test_QS_QUEUE_get_elem_1
		end

	test_QS_QUEUE_make_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 0)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 0)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			 -- No sequence for array Current.queue found in the counterexample. 

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			current_object.make
		end

	test_QS_QUEUE_enter_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			data: INTEGER_32
			bn: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 100)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			data := -2147451757
			bn := 1
			current_object.enter (data, bn)
		end

	test_QS_QUEUE_enter_2
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			data: INTEGER_32
			bn: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 101)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			data := -2147451757
			bn := 2
			current_object.enter (data, bn)
		end

	test_QS_QUEUE_delete_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			delete_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 19)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 3
			delete_result := current_object.delete (bn)
		end

	test_QS_QUEUE_delete_2
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			delete_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 93)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (-2147464507, 1)
			current_object_queue.force (-2147464507, 2)
			current_object_queue.force (-2147464507, 3)
			current_object_queue.force (-2147464507, 4)
			current_object_queue.force (-2147464507, 5)
			current_object_queue.force (-2147464507, 6)
			current_object_queue.force (-2147464507, 7)
			current_object_queue.force (-2147464507, 8)
			current_object_queue.force (-2147464507, 9)
			current_object_queue.force (-2147464507, 10)
			current_object_queue.force (-2147464507, 11)
			current_object_queue.force (-2147464507, 12)
			current_object_queue.force (-2147464507, 13)
			current_object_queue.force (-2147464507, 14)
			current_object_queue.force (-2147464507, 15)
			current_object_queue.force (-2147464507, 16)
			current_object_queue.force (-2147464507, 17)
			current_object_queue.force (-2147464507, 18)
			current_object_queue.force (-2147464507, 19)
			current_object_queue.force (-2147464507, 20)
			current_object_queue.force (-2147464507, 21)
			current_object_queue.force (-2147464507, 22)
			current_object_queue.force (-2147464507, 23)
			current_object_queue.force (-2147464507, 24)
			current_object_queue.force (-2147464507, 25)
			current_object_queue.force (-2147464507, 26)
			current_object_queue.force (-2147464507, 27)
			current_object_queue.force (-2147464507, 28)
			current_object_queue.force (-2147464507, 29)
			current_object_queue.force (-2147464507, 30)
			current_object_queue.force (-2147464507, 31)
			current_object_queue.force (-2147464507, 32)
			current_object_queue.force (-2147464507, 33)
			current_object_queue.force (-2147464507, 34)
			current_object_queue.force (-2147464507, 35)
			current_object_queue.force (-2147464507, 36)
			current_object_queue.force (-2147464507, 37)
			current_object_queue.force (-2147464507, 38)
			current_object_queue.force (-2147464507, 39)
			current_object_queue.force (-2147464507, 40)
			current_object_queue.force (-2147464507, 41)
			current_object_queue.force (-2147464507, 42)
			current_object_queue.force (-2147464507, 43)
			current_object_queue.force (-2147464507, 44)
			current_object_queue.force (-2147464507, 45)
			current_object_queue.force (-2147464507, 46)
			current_object_queue.force (-2147464507, 47)
			current_object_queue.force (-2147464507, 48)
			current_object_queue.force (-2147464507, 49)
			current_object_queue.force (-2147464507, 50)
			current_object_queue.force (-2147464507, 51)
			current_object_queue.force (-2147464507, 52)
			current_object_queue.force (-2147464507, 53)
			current_object_queue.force (-2147464507, 54)
			current_object_queue.force (-2147464507, 55)
			current_object_queue.force (-2147464507, 56)
			current_object_queue.force (-2147464507, 57)
			current_object_queue.force (-2147464507, 58)
			current_object_queue.force (-2147464507, 59)
			current_object_queue.force (-2147464507, 60)
			current_object_queue.force (-2147464507, 61)
			current_object_queue.force (-2147464507, 62)
			current_object_queue.force (-2147464507, 63)
			current_object_queue.force (-2147464507, 64)
			current_object_queue.force (-2147464507, 65)
			current_object_queue.force (-2147464507, 66)
			current_object_queue.force (-2147464507, 67)
			current_object_queue.force (-2147464507, 68)
			current_object_queue.force (-2147464507, 69)
			current_object_queue.force (-2147464507, 70)
			current_object_queue.force (-2147464507, 71)
			current_object_queue.force (-2147464507, 72)
			current_object_queue.force (-2147464507, 73)
			current_object_queue.force (-2147464507, 74)
			current_object_queue.force (-2147464507, 75)
			current_object_queue.force (-2147464507, 76)
			current_object_queue.force (-2147464507, 77)
			current_object_queue.force (-2147464507, 78)
			current_object_queue.force (-2147464507, 79)
			current_object_queue.force (-2147464507, 80)
			current_object_queue.force (-2147464507, 81)
			current_object_queue.force (-2147464507, 82)
			current_object_queue.force (-2147464507, 83)
			current_object_queue.force (-2147464507, 84)
			current_object_queue.force (-2147464507, 85)
			current_object_queue.force (-2147464507, 86)
			current_object_queue.force (-2147464507, 87)
			current_object_queue.force (-2147464507, 88)
			current_object_queue.force (-2147464507, 89)
			current_object_queue.force (-2147464507, 90)
			current_object_queue.force (-2147464507, 91)
			current_object_queue.force (-2147464507, 92)
			current_object_queue.force (-2147464507, 93)
			current_object_queue.force (-2147464507, 94)
			current_object_queue.force (-2147464507, 95)
			current_object_queue.force (-2147464507, 96)
			current_object_queue.force (-2147464507, 97)
			current_object_queue.force (-2147464507, 98)
			current_object_queue.force (-2147464507, 99)
			current_object_queue.force (-2147464507, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 4
			delete_result := current_object.delete (bn)
		end

	test_QS_QUEUE_delete_3
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			delete_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 1)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 5
			delete_result := current_object.delete (bn)
		end

	test_QS_QUEUE_peek_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			peek_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 59)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 6
			peek_result := current_object.peek (bn)
		end

	test_QS_QUEUE_peek_2
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			peek_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 1)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 7
			peek_result := current_object.peek (bn)
		end

	test_QS_QUEUE_is_contain_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			key: INTEGER_32
			bn: INTEGER_32
			is_contain_result: BOOLEAN
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 101)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force ((-2147467773), 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			key := -2147467773
			bn := 8
			is_contain_result := current_object.is_contain (key, bn)
		end

	test_QS_QUEUE_is_contain_2
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			key: INTEGER_32
			bn: INTEGER_32
			is_contain_result: BOOLEAN
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 101)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force ((-2147451492), 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			key := -2147451491
			bn := 9
			is_contain_result := current_object.is_contain (key, bn)
		end

	test_QS_QUEUE_search_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			key: INTEGER_32
			bn: INTEGER_32
			search_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 101)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			key := 0
			bn := 10
			search_result := current_object.search (key, bn)
		end

	test_QS_QUEUE_search_2
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			key: INTEGER_32
			bn: INTEGER_32
			search_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 101)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force ((-2147473521), 93)
			current_object_queue.force ((-2147473521), 94)
			current_object_queue.force ((-2147473521), 95)
			current_object_queue.force ((-2147473521), 96)
			current_object_queue.force ((-2147473521), 97)
			current_object_queue.force ((-2147473521), 98)
			current_object_queue.force ((-2147473521), 99)
			current_object_queue.force ((-2147473521), 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			key := -2147473522
			bn := 11
			search_result := current_object.search (key, bn)
		end

	test_QS_QUEUE_is_empty_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			is_empty_result: BOOLEAN
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 48)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := -2147451363
			is_empty_result := current_object.is_empty (bn)
		end

	test_QS_QUEUE_is_full_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			is_full_result: BOOLEAN
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 101)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 12
			is_full_result := current_object.is_full (bn)
		end

	test_QS_QUEUE_is_full_2
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			bn: INTEGER_32
			is_full_result: BOOLEAN
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 100)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			bn := 13
			is_full_result := current_object.is_full (bn)
		end

	test_QS_QUEUE_size_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			size_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 48)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			size_result := current_object.size
		end

	test_QS_QUEUE_get_front_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			get_front_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 48)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			get_front_result := current_object.get_front
		end

	test_QS_QUEUE_get_rear_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			get_rear_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 48)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			get_rear_result := current_object.get_rear
		end

	test_QS_QUEUE_get_elem_1
		local 
			current_object: QS_QUEUE
			current_object_queue: SIMPLE_ARRAY [INTEGER_32]
			i: INTEGER_32
			get_elem_result: INTEGER_32
		do
			create current_object.make
			{P_INTERNAL}.set_integer_32_field_ ("front", current_object, 1)
			{P_INTERNAL}.set_integer_32_field_ ("rear", current_object, 89)
			{P_INTERNAL}.set_boolean_field_ ("exception_is_raised", current_object, false)
			create current_object_queue.make_empty
			current_object_queue.force (0, 1)
			current_object_queue.force (0, 2)
			current_object_queue.force (0, 3)
			current_object_queue.force (0, 4)
			current_object_queue.force (0, 5)
			current_object_queue.force (0, 6)
			current_object_queue.force (0, 7)
			current_object_queue.force (0, 8)
			current_object_queue.force (0, 9)
			current_object_queue.force (0, 10)
			current_object_queue.force (0, 11)
			current_object_queue.force (0, 12)
			current_object_queue.force (0, 13)
			current_object_queue.force (0, 14)
			current_object_queue.force (0, 15)
			current_object_queue.force (0, 16)
			current_object_queue.force (0, 17)
			current_object_queue.force (0, 18)
			current_object_queue.force (0, 19)
			current_object_queue.force (0, 20)
			current_object_queue.force (0, 21)
			current_object_queue.force (0, 22)
			current_object_queue.force (0, 23)
			current_object_queue.force (0, 24)
			current_object_queue.force (0, 25)
			current_object_queue.force (0, 26)
			current_object_queue.force (0, 27)
			current_object_queue.force (0, 28)
			current_object_queue.force (0, 29)
			current_object_queue.force (0, 30)
			current_object_queue.force (0, 31)
			current_object_queue.force (0, 32)
			current_object_queue.force (0, 33)
			current_object_queue.force (0, 34)
			current_object_queue.force (0, 35)
			current_object_queue.force (0, 36)
			current_object_queue.force (0, 37)
			current_object_queue.force (0, 38)
			current_object_queue.force (0, 39)
			current_object_queue.force (0, 40)
			current_object_queue.force (0, 41)
			current_object_queue.force (0, 42)
			current_object_queue.force (0, 43)
			current_object_queue.force (0, 44)
			current_object_queue.force (0, 45)
			current_object_queue.force (0, 46)
			current_object_queue.force (0, 47)
			current_object_queue.force (0, 48)
			current_object_queue.force (0, 49)
			current_object_queue.force (0, 50)
			current_object_queue.force (0, 51)
			current_object_queue.force (0, 52)
			current_object_queue.force (0, 53)
			current_object_queue.force (0, 54)
			current_object_queue.force (0, 55)
			current_object_queue.force (0, 56)
			current_object_queue.force (0, 57)
			current_object_queue.force (0, 58)
			current_object_queue.force (0, 59)
			current_object_queue.force (0, 60)
			current_object_queue.force (0, 61)
			current_object_queue.force (0, 62)
			current_object_queue.force (0, 63)
			current_object_queue.force (0, 64)
			current_object_queue.force (0, 65)
			current_object_queue.force (0, 66)
			current_object_queue.force (0, 67)
			current_object_queue.force (0, 68)
			current_object_queue.force (0, 69)
			current_object_queue.force (0, 70)
			current_object_queue.force (0, 71)
			current_object_queue.force (0, 72)
			current_object_queue.force (0, 73)
			current_object_queue.force (0, 74)
			current_object_queue.force (0, 75)
			current_object_queue.force (0, 76)
			current_object_queue.force (0, 77)
			current_object_queue.force (0, 78)
			current_object_queue.force (0, 79)
			current_object_queue.force (0, 80)
			current_object_queue.force (0, 81)
			current_object_queue.force (0, 82)
			current_object_queue.force (0, 83)
			current_object_queue.force (0, 84)
			current_object_queue.force (0, 85)
			current_object_queue.force (0, 86)
			current_object_queue.force (0, 87)
			current_object_queue.force (0, 88)
			current_object_queue.force (0, 89)
			current_object_queue.force (0, 90)
			current_object_queue.force (0, 91)
			current_object_queue.force (0, 92)
			current_object_queue.force (0, 93)
			current_object_queue.force (0, 94)
			current_object_queue.force (0, 95)
			current_object_queue.force (0, 96)
			current_object_queue.force (0, 97)
			current_object_queue.force (0, 98)
			current_object_queue.force (0, 99)
			current_object_queue.force (0, 100)

			{P_INTERNAL}.set_reference_field_ ("queue", current_object, current_object_queue)
			i := 88
			get_elem_result := current_object.get_elem (i)
		end

end
